
unused = "#79e11a"

[default]
  black = "#000000"
  base01 = "#373844"
  base02 = "#464752"
  base03 = "#565761"
  base04 = "#969692"
  base05 = "#ccccc7"
  base06 = "#e2e2dc"
  white = "#ffffff"
  red = "#ff0000"
  orange = "#ffa42c"
  yellow = "#ffff00"
  green = "#5fff00"
  cyan = "#0087ff"
  blue = "#0000ff"
  brightblue = "#0084fb"
  purple = "#800080"
  magenta = "#8b008b"

[dark]
  button = ["default.black","default.base04"]
  button-focus = ["default.white","default.magenta"]
  button-selected = ["default.white","default.base04"]
  cmdline = ["default.black","default.yellow"]
  cmdline-button = ["default.yellow","default.black"]
  cmdline-border = ["default.black","default.yellow"]
  copy-mode = ["default.black","default.yellow"]
  copy-mode-alt = ["default.yellow","default.black"]
  copy-mode-label = ["default.white","default.red"]
  current-capture = ["default.white","themes.unused"]
  dialog = ["default.black","default.yellow"]
  dialog-button = ["default.yellow","default.black"]
  default = ["default.white","default.black"]
  filter-intermediate = ["default.black","default.orange"]
  filter-invalid = ["default.black","default.red"]
  filter-menu = ["default.white","default.black"]
  filter-valid = ["default.black","default.green"]
  hex-byte-selected = ["default.white","default.purple"]
  hex-byte-unselected = ["default.white","default.black"]
  hex-field-selected = ["default.black","default.cyan"]
  hex-field-unselected = ["default.black","default.white"]
  hex-interval-selected = ["default.white","default.base03"]
  hex-interval-unselected = ["default.white","default.base02"]
  hex-layer-selected = ["default.white","default.base03"]
  hex-layer-unselected = ["default.white","default.base02"]
  packet-list-cell-focus = ["default.white","default.purple"]
  packet-list-cell-selected = ["default.white","default.base03"]
  packet-list-row-focus = ["default.white","default.brightblue"]
  packet-list-row-selected = ["default.white","default.base02"]
  packet-struct-focus = ["default.white","default.brightblue"]
  packet-struct-selected = ["default.black","default.base03"]
  progress-complete = ["default.white","default.purple"]
  progress-default = ["default.white","default.black"]
  progress-spinner = ["default.yellow","default.purple"]
  spinner = ["default.yellow","default.black"]
  stream-client = ["default.black","default.red"]
  stream-match = ["default.black","default.yellow"]
  stream-search = ["default.black","default.white"]
  stream-server = ["default.cyan","default.blue"]
  title = ["default.red","unused"]

[light]
  button = ["default.black","default.white"]
  button-focus = ["default.black","default.purple"]
  button-selected = ["default.black","default.base04"]
  cmdline = ["default.black","default.yellow"]
  cmdline-button = ["default.yellow","default.black"]
  cmdline-border = ["default.black","default.yellow"]
  copy-mode = ["default.white","default.yellow"]
  copy-mode-alt = ["default.yellow","default.white"]
  copy-mode-label = ["default.black","default.red"]
  current-capture = ["default.black","unused"]
  dialog = ["default.black","default.yellow"]
  dialog-button = ["default.yellow","default.black"]
  default = ["default.black","default.white"]
  filter-intermediate = ["default.black","default.orange"]
  filter-invalid = ["default.black","default.red"]
  filter-menu = ["default.black","default.white"]
  filter-valid = ["default.black","default.green"]
  hex-byte-selected = ["default.white","default.purple"]
  hex-byte-unselected = ["default.black","default.white"]
  hex-field-selected = ["default.black","default.cyan"]
  hex-field-unselected = ["default.black","default.base03"]
  hex-interval-selected = ["default.white","default.base03"]
  hex-interval-unselected = ["default.black","default.base05"]
  hex-layer-selected = ["default.white","default.base03"]
  hex-layer-unselected = ["default.black","default.base05"]
  packet-list-cell-focus = ["default.white","default.purple"]
  packet-list-cell-selected = ["default.black","default.base04"]
  packet-list-row-focus = ["default.white","default.brightblue"]
  packet-list-row-selected = ["default.black","default.base05"]
  packet-struct-focus = ["default.white","default.brightblue"]
  packet-struct-selected = ["default.black","default.base05"]
  progress-complete = ["default.white","default.purple"]
  progress-default = ["default.white","default.black"]
  progress-spinner = ["default.yellow","default.black"]
  spinner = ["default.yellow","default.white"]
  stream-client = ["default.white","default.red"]
  stream-match = ["default.white","default.yellow"]
  stream-search = ["default.white","default.black"]
  stream-server = ["default.cyan","default.blue"]
  title = ["default.red","unused"]
