
unused = "#79e11a"

[dracula]
  base00 = "#282a36"
  base01 = "#373844"
  base02 = "#464752"
  base03 = "#565761"
  base04 = "#b6b6b2"
  base05 = "#ccccc7"
  base06 = "#e2e2dc"
  base07 = "#f8f8f2"
  base08 = "#ff5555"
  base09 = "#ffb86c"
  base0a = "#f1fa8c"
  base0b = "#50fa7b"
  base0c = "#8be9fd"
  base0d = "#6272a4"
  base0e = "#bd93f9"
  base0f = "#ff79c6"
  black = "dracula.base00"
  blue = "dracula.base0d"
  cyan = "dracula.base0c"
  green = "dracula.base0b"
  magenta = "dracula.base0f"
  orange = "dracula.base09"
  purple = "dracula.base0e"
  red = "dracula.base08"
  white = "dracula.base07"
  yellow = "dracula.base0a"

[dark]
  button = ["dracula.white","dracula.black"]
  button-focus = ["dracula.black","dracula.purple"]
  button-selected = ["dracula.white","dracula.black"]
  cmdline = ["dracula.black","dracula.yellow"]
  cmdline-button = ["dracula.yellow","dracula.black"]
  copy-mode = ["dracula.black","dracula.yellow"]
  copy-mode-alt = ["dracula.yellow","dracula.black"]
  copy-mode-label = ["dracula.white","dracula.red"]
  current-capture = ["dracula.white","themes.unused"]
  dialog = ["dracula.black","dracula.yellow"]
  dialog-button = ["dracula.yellow","dracula.black"]
  default = ["dracula.white","dracula.black"]
  filter-intermediate = ["dracula.black","dracula.orange"]
  filter-invalid = ["dracula.black","dracula.red"]
  filter-menu = ["dracula.white","dracula.black"]
  filter-valid = ["dracula.black","dracula.green"]
  hex-byte-selected = ["dracula.black","dracula.purple"]
  hex-byte-unselected = ["dracula.white","dracula.black"]
  hex-field-selected = ["dracula.black","dracula.cyan"]
  hex-field-unselected = ["dracula.black","dracula.white"]
  hex-interval-selected = ["dracula.white","dracula.base03"]
  hex-interval-unselected = ["dracula.white","dracula.base02"]
  hex-layer-selected = ["dracula.white","dracula.base03"]
  hex-layer-unselected = ["dracula.white","dracula.base02"]
  packet-list-cell-focus = ["dracula.black","dracula.purple"]
  packet-list-cell-selected = ["dracula.white","dracula.base03"]
  packet-list-row-focus = ["dracula.base03","dracula.cyan"]
  packet-list-row-selected = ["dracula.white","dracula.base02"]
  packet-struct-focus = ["dracula.black","dracula.cyan"]
  packet-struct-selected = ["dracula.black","dracula.base03"]
  progress-complete = ["dracula.white","dracula.purple"]
  progress-default = ["dracula.white","dracula.black"]
  progress-spinner = ["dracula.yellow","dracula.purple"]
  spinner = ["dracula.yellow","dracula.black"]
  stream-client = ["dracula.black","dracula.red"]
  stream-match = ["dracula.black","dracula.yellow"]
  stream-search = ["dracula.black","dracula.white"]
  stream-server = ["dracula.cyan","dracula.blue"]
  title = ["dracula.red","themes.unused"]

[light]
  button = ["dracula.black","dracula.white"]
  button-focus = ["dracula.black","dracula.purple"]
  button-selected = ["dracula.black","dracula.base04"]
  cmdline = ["dracula.black","dracula.yellow"]
  cmdline-button = ["dracula.yellow","dracula.black"]
  copy-mode = ["dracula.white","dracula.yellow"]
  copy-mode-alt = ["dracula.yellow","dracula.white"]
  copy-mode-label = ["dracula.black","dracula.red"]
  current-capture = ["dracula.black","themes.unused"]
  dialog = ["dracula.black","dracula.yellow"]
  dialog-button = ["dracula.yellow","dracula.black"]
  default = ["dracula.black","dracula.white"]
  filter-intermediate = ["dracula.black","dracula.orange"]
  filter-invalid = ["dracula.black","dracula.red"]
  filter-menu = ["dracula.black","dracula.white"]
  filter-valid = ["dracula.black","dracula.green"]
  hex-byte-selected = ["dracula.black","dracula.purple"]
  hex-byte-unselected = ["dracula.black","dracula.white"]
  hex-field-selected = ["dracula.black","dracula.cyan"]
  hex-field-unselected = ["dracula.black","dracula.base03"]
  hex-interval-selected = ["dracula.white","dracula.base03"]
  hex-interval-unselected = ["dracula.black","dracula.base05"]
  hex-layer-selected = ["dracula.white","dracula.base03"]
  hex-layer-unselected = ["dracula.black","dracula.base05"]
  packet-list-cell-focus = ["dracula.black","dracula.purple"]
  packet-list-cell-selected = ["dracula.black","dracula.base04"]
  packet-list-row-focus = ["dracula.black","dracula.cyan"]
  packet-list-row-selected = ["dracula.black","dracula.base05"]
  packet-struct-focus = ["dracula.black","dracula.cyan"]
  packet-struct-selected = ["dracula.black","dracula.base05"]
  progress-complete = ["dracula.white","dracula.purple"]
  progress-default = ["dracula.white","dracula.black"]
  progress-spinner = ["dracula.yellow","dracula.black"]
  spinner = ["dracula.yellow","dracula.white"]
  stream-client = ["dracula.white","dracula.red"]
  stream-match = ["dracula.white","dracula.yellow"]
  stream-search = ["dracula.white","dracula.black"]
  stream-server = ["dracula.cyan","dracula.blue"]
  title = ["dracula.red","themes.unused"]
