
unused = "#79e11a"

[solarized]
  base00 = "#002b36"
  base01 = "#073642"
  base02 = "#586e75"
  base03 = "#657b83"
  base04 = "#839496"
  base05 = "#93a1a1"
  base06 = "#eee8d5"
  base07 = "#fdf6e3"
  base08 = "#dc322f"
  base09 = "#cb4b16"
  base0a = "#B58900"
  base0b = "#859900"
  base0c = "#2aa198"
  base0d = "#268bd2"
  base0e = "#6c71c4"
  base0f = "#d33682"
  black = "solarized.base00"
  blue = "solarized.base0d"
  cyan = "solarized.base0c"
  green = "solarized.base0b"
  magenta = "solarized.base0f"
  orange = "solarized.base09"
  purple = "solarized.base0e"
  red = "solarized.base08"
  white = "solarized.base07"
  yellow = "solarized.base0a"

[dark]
  button = ["solarized.white","solarized.black"]
  button-focus = ["solarized.black","solarized.purple"]
  button-selected = ["solarized.white","solarized.black"]
  cmdline = ["solarized.black","solarized.yellow"]
  cmdline-button = ["solarized.yellow","solarized.black"]
  cmdline-border = ["solarized.black","solarized.yellow"]
  copy-mode = ["solarized.black","solarized.yellow"]
  copy-mode-alt = ["solarized.yellow","solarized.black"]
  copy-mode-label = ["solarized.white","solarized.red"]
  current-capture = ["solarized.white","unused"]
  dialog = ["solarized.black","solarized.yellow"]
  dialog-button = ["solarized.yellow","solarized.black"]
  default = ["solarized.white","solarized.black"]
  filter-intermediate = ["solarized.black","solarized.orange"]
  filter-invalid = ["solarized.black","solarized.red"]
  filter-menu = ["solarized.white","solarized.black"]
  filter-valid = ["solarized.black","solarized.green"]
  hex-byte-selected = ["solarized.black","solarized.purple"]
  hex-byte-unselected = ["solarized.white","solarized.black"]
  hex-field-selected = ["solarized.black","solarized.cyan"]
  hex-field-unselected = ["solarized.black","solarized.white"]
  hex-interval-selected = ["solarized.white","solarized.base03"]
  hex-interval-unselected = ["solarized.white","solarized.base02"]
  hex-layer-selected = ["solarized.white","solarized.base03"]
  hex-layer-unselected = ["solarized.white","solarized.base02"]
  packet-list-cell-focus = ["solarized.black","solarized.purple"]
  packet-list-cell-selected = ["solarized.white","solarized.base03"]
  packet-list-row-focus = ["solarized.base03","solarized.cyan"]
  packet-list-row-selected = ["solarized.white","solarized.base02"]
  packet-struct-focus = ["solarized.black","solarized.cyan"]
  packet-struct-selected = ["solarized.black","solarized.base03"]
  progress-complete = ["solarized.white","solarized.purple"]
  progress-default = ["solarized.white","solarized.black"]
  progress-spinner = ["solarized.yellow","solarized.purple"]
  spinner = ["solarized.yellow","solarized.black"]
  stream-client = ["solarized.black","solarized.red"]
  stream-match = ["solarized.black","solarized.yellow"]
  stream-search = ["solarized.black","solarized.white"]
  stream-server = ["solarized.cyan","solarized.blue"]
  title = ["solarized.red","unused"]

[light]
  button = ["solarized.black","solarized.white"]
  button-focus = ["solarized.black","solarized.purple"]
  button-selected = ["solarized.black","solarized.base04"]
  cmdline = ["solarized.black","solarized.yellow"]
  cmdline-button = ["solarized.yellow","solarized.black"]
  cmdline-border = ["solarized.black","solarized.yellow"]
  copy-mode = ["solarized.white","solarized.yellow"]
  copy-mode-alt = ["solarized.yellow","solarized.white"]
  copy-mode-label = ["solarized.black","solarized.red"]
  current-capture = ["solarized.black","unused"]
  dialog = ["solarized.black","solarized.yellow"]
  dialog-button = ["solarized.yellow","solarized.black"]
  default = ["solarized.black","solarized.white"]
  filter-intermediate = ["solarized.black","solarized.orange"]
  filter-invalid = ["solarized.black","solarized.red"]
  filter-menu = ["solarized.black","solarized.white"]
  filter-valid = ["solarized.black","solarized.green"]
  hex-byte-selected = ["solarized.black","solarized.purple"]
  hex-byte-unselected = ["solarized.black","solarized.white"]
  hex-field-selected = ["solarized.black","solarized.cyan"]
  hex-field-unselected = ["solarized.black","solarized.base03"]
  hex-interval-selected = ["solarized.white","solarized.base03"]
  hex-interval-unselected = ["solarized.black","solarized.base05"]
  hex-layer-selected = ["solarized.white","solarized.base03"]
  hex-layer-unselected = ["solarized.black","solarized.base05"]
  packet-list-cell-focus = ["solarized.black","solarized.purple"]
  packet-list-cell-selected = ["solarized.black","solarized.base04"]
  packet-list-row-focus = ["solarized.black","solarized.cyan"]
  packet-list-row-selected = ["solarized.black","solarized.base05"]
  packet-struct-focus = ["solarized.black","solarized.cyan"]
  packet-struct-selected = ["solarized.black","solarized.base05"]
  progress-complete = ["solarized.white","solarized.purple"]
  progress-default = ["solarized.white","solarized.black"]
  progress-spinner = ["solarized.yellow","solarized.black"]
  spinner = ["solarized.yellow","solarized.white"]
  stream-client = ["solarized.white","solarized.red"]
  stream-match = ["solarized.white","solarized.yellow"]
  stream-search = ["solarized.white","solarized.black"]
  stream-server = ["solarized.cyan","solarized.blue"]
  title = ["solarized.red","unused"]

